---
title: "03-data_ingest-ACS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(lubridate)
library(janitor)
library(jsonlite)
library(httr)
library(rlist)
library(dplyr)
```

```{r}
acs <- read_csv("data_and_cleaning/raw_data/raw_ACS_Economic_Characteristics_DC_Ward.csv", 
     col_types = cols(`EMPLOYMENT STATUS: Population 16 years and over: In Labor Force` = col_integer(), 
         `COMMUTING TO WORK: Workers 16 years and over\n` = col_integer(), 
         `INDUSTRY: Civilian employed population 16 years and over: Educational services, and health care and social assistance\n` = col_integer(), 
         `INCOME AND BENEFITS (IN 2020 INFLATION-ADJUSTED DOLLARS): Total households: With earnings: Mean earnings (dollars)\n` = col_integer()))
acs
```

```{r}
# cleaning
janitor::clean_names(dat = acs) -> acs
acs
```
```{r}
# names too long
acs_clean <- acs %>%
  rename(
    employment = employment_status_population_16_years_and_over_in_labor_force,
    commuting = commuting_to_work_workers_16_years_and_over,
    industry_education_health = industry_civilian_employed_population_16_years_and_over_educational_services_and_health_care_and_social_assistance,
    mean_income = income_and_benefits_in_2020_inflation_adjusted_dollars_total_households_with_earnings_mean_earnings_dollars,
    ward = namelsad
  ) 
acs_clean <- select(acs_clean, -c(name))
acs_clean
```

```{r}
write_csv(acs_clean, file = "./acs_clean.csv")
```
