---
title: "Untitled"
author: "Michael Lewis"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
read_csv("../data_and_cleaning/acs_clean.csv") -> ACS

read_csv("../data_and_cleaning/dc_covid_clean.csv") %>% 
  filter(date < "2020-12-31") %>% 
  filter(date > "2020-01-01") %>%
  mutate(ward = as_factor(ward)) -> COVID
```

```{r}
left_join(COVID, ACS) -> combined #by ward
```


```{r}
lm(combined$lives_lost ~ combined$ward + combined$total_tests ) -> full_model
summary(full_model)

```

```{r}
# Ward Level

ward_analysis <- function(number) {
  COVID %>% filter(ward == number) -> W
lm(combined$lives_lost ~ combined$total_tests + combined$employment + combined$commuting + combined$industry_education_health + combined$mean_income) -> W_model
return(W_model)
}

wards <- unique(combined$ward)
wards

ward_analysis("Ward 1") -> ward1_model
ward_analysis("Ward 2") -> ward2_model
ward_analysis("Ward 3") -> ward3_model
ward_analysis("Ward 4") -> ward4_model
ward_analysis("Ward 5") -> ward5_model
ward_analysis("Ward 6") -> ward6_model
ward_analysis("Ward 7") -> ward7_model
ward_analysis("Ward 8") -> ward8_model
ward_analysis("Homeless") -> Homeless_model
ward_analysis("All") -> All_model

```

